# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variables.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VariablesWindow(object):
    def setupUi(self, VariablesWindow):
        VariablesWindow.setObjectName("VariablesWindow")
        VariablesWindow.resize(324, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VariablesWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VariablesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.labelOxTank = QtWidgets.QLabel(self.centralwidget)
        self.labelOxTank.setObjectName("labelOxTank")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelOxTank)
        self.SpinBoxOxTank = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxOxTank.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SpinBoxOxTank.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxOxTank.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxOxTank.setProperty("showGroupSeparator", False)
        self.SpinBoxOxTank.setDecimals(5)
        self.SpinBoxOxTank.setObjectName("SpinBoxOxTank")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SpinBoxOxTank)
        self.labelThroatA = QtWidgets.QLabel(self.centralwidget)
        self.labelThroatA.setObjectName("labelThroatA")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelThroatA)
        self.SpinBoxThroatA = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxThroatA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxThroatA.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxThroatA.setDecimals(5)
        self.SpinBoxThroatA.setObjectName("SpinBoxThroatA")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SpinBoxThroatA)
        self.labelExitA = QtWidgets.QLabel(self.centralwidget)
        self.labelExitA.setObjectName("labelExitA")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelExitA)
        self.SpinBoxExitA = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxExitA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxExitA.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxExitA.setDecimals(5)
        self.SpinBoxExitA.setMaximum(1000.0)
        self.SpinBoxExitA.setObjectName("SpinBoxExitA")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SpinBoxExitA)
        self.labelInjA = QtWidgets.QLabel(self.centralwidget)
        self.labelInjA.setObjectName("labelInjA")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelInjA)
        self.SpinBoxInjA = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxInjA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxInjA.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxInjA.setDecimals(5)
        self.SpinBoxInjA.setMaximum(1000.0)
        self.SpinBoxInjA.setObjectName("SpinBoxInjA")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SpinBoxInjA)
        self.labelOxfuel = QtWidgets.QLabel(self.centralwidget)
        self.labelOxfuel.setObjectName("labelOxfuel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelOxfuel)
        self.SpinBoxOxFuel = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxOxFuel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxOxFuel.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxOxFuel.setDecimals(3)
        self.SpinBoxOxFuel.setObjectName("SpinBoxOxFuel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SpinBoxOxFuel)
        self.labelRampUp = QtWidgets.QLabel(self.centralwidget)
        self.labelRampUp.setObjectName("labelRampUp")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelRampUp)
        self.SpinBoxRampUp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxRampUp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SpinBoxRampUp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxRampUp.setDecimals(1)
        self.SpinBoxRampUp.setMaximum(60.0)
        self.SpinBoxRampUp.setObjectName("SpinBoxRampUp")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SpinBoxRampUp)
        self.labelRampDown = QtWidgets.QLabel(self.centralwidget)
        self.labelRampDown.setObjectName("labelRampDown")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelRampDown)
        self.SpinBoxRampDown = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxRampDown.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SpinBoxRampDown.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxRampDown.setDecimals(1)
        self.SpinBoxRampDown.setMaximum(60.0)
        self.SpinBoxRampDown.setObjectName("SpinBoxRampDown")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.SpinBoxRampDown)
        self.labelTimeStep = QtWidgets.QLabel(self.centralwidget)
        self.labelTimeStep.setObjectName("labelTimeStep")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelTimeStep)
        self.SpinBoxTimeStep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxTimeStep.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.SpinBoxTimeStep.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxTimeStep.setDecimals(3)
        self.SpinBoxTimeStep.setMaximum(1.0)
        self.SpinBoxTimeStep.setSingleStep(0.005)
        self.SpinBoxTimeStep.setObjectName("SpinBoxTimeStep")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.SpinBoxTimeStep)
        self.labelConvWeight = QtWidgets.QLabel(self.centralwidget)
        self.labelConvWeight.setObjectName("labelConvWeight")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelConvWeight)
        self.SpinBoxConverge = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxConverge.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxConverge.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxConverge.setDecimals(3)
        self.SpinBoxConverge.setMaximum(1.0)
        self.SpinBoxConverge.setObjectName("SpinBoxConverge")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.SpinBoxConverge)
        self.labelVaporization = QtWidgets.QLabel(self.centralwidget)
        self.labelVaporization.setObjectName("labelVaporization")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelVaporization)
        self.SpinBoxVaporFactor = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxVaporFactor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxVaporFactor.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxVaporFactor.setDecimals(3)
        self.SpinBoxVaporFactor.setMaximum(1.0)
        self.SpinBoxVaporFactor.setObjectName("SpinBoxVaporFactor")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.SpinBoxVaporFactor)
        self.labelFlowModel = QtWidgets.QLabel(self.centralwidget)
        self.labelFlowModel.setObjectName("labelFlowModel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelFlowModel)
        self.checkBoxFlowModel = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFlowModel.setText("")
        self.checkBoxFlowModel.setChecked(False)
        self.checkBoxFlowModel.setObjectName("checkBoxFlowModel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.checkBoxFlowModel)
        self.labelIntType = QtWidgets.QLabel(self.centralwidget)
        self.labelIntType.setObjectName("labelIntType")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.labelIntType)
        self.checkBoxIntType = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxIntType.setText("")
        self.checkBoxIntType.setChecked(False)
        self.checkBoxIntType.setTristate(False)
        self.checkBoxIntType.setObjectName("checkBoxIntType")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkBoxIntType)
        self.labelCalcCf = QtWidgets.QLabel(self.centralwidget)
        self.labelCalcCf.setObjectName("labelCalcCf")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.labelCalcCf)
        self.checkBoxCalcCf = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCalcCf.setText("")
        self.checkBoxCalcCf.setObjectName("checkBoxCalcCf")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.checkBoxCalcCf)
        self.labelC12 = QtWidgets.QLabel(self.centralwidget)
        self.labelC12.setObjectName("labelC12")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.labelC12)
        self.SpinBoxC12 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxC12.setReadOnly(False)
        self.SpinBoxC12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SpinBoxC12.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBoxC12.setDecimals(3)
        self.SpinBoxC12.setObjectName("SpinBoxC12")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.SpinBoxC12)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        VariablesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VariablesWindow)
        self.statusbar.setObjectName("statusbar")
        VariablesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VariablesWindow)
        self.buttonBox.clicked['QAbstractButton*'].connect(VariablesWindow.close)
        QtCore.QMetaObject.connectSlotsByName(VariablesWindow)

    def retranslateUi(self, VariablesWindow):
        _translate = QtCore.QCoreApplication.translate
        VariablesWindow.setWindowTitle(_translate("VariablesWindow", "Variables"))
        self.labelOxTank.setText(_translate("VariablesWindow", "Oxidizer Tank Volume (L)"))
        self.labelThroatA.setText(_translate("VariablesWindow", "Nozzle Throat Area (cm²)"))
        self.labelExitA.setText(_translate("VariablesWindow", "Nozzle Exit Area (cm²)"))
        self.labelInjA.setText(_translate("VariablesWindow", "Injector Area (cm²)"))
        self.labelOxfuel.setText(_translate("VariablesWindow", "Average O/F Ratio"))
        self.labelRampUp.setText(_translate("VariablesWindow", "Ramp Up Time (s)"))
        self.labelRampDown.setText(_translate("VariablesWindow", "Ramp Down Time (s)"))
        self.labelTimeStep.setText(_translate("VariablesWindow", "Time Step (s)"))
        self.labelConvWeight.setText(_translate("VariablesWindow", "Convergence Weighting"))
        self.labelVaporization.setText(_translate("VariablesWindow", "Vaporization Factor"))
        self.labelFlowModel.setText(_translate("VariablesWindow", "Use Converging Flow Model"))
        self.labelIntType.setText(_translate("VariablesWindow", "Use Addam\'s Integration"))
        self.labelCalcCf.setText(_translate("VariablesWindow", "Calculate Cf"))
        self.labelC12.setText(_translate("VariablesWindow", "C12"))

