# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/variables.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VariablesWindow(object):
    def setupUi(self, VariablesWindow):
        VariablesWindow.setObjectName("VariablesWindow")
        VariablesWindow.resize(299, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VariablesWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VariablesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.labelOxTank = QtWidgets.QLabel(self.centralwidget)
        self.labelOxTank.setObjectName("labelOxTank")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelOxTank)
        self.lineEditOxTank = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOxTank.sizePolicy().hasHeightForWidth())
        self.lineEditOxTank.setSizePolicy(sizePolicy)
        self.lineEditOxTank.setObjectName("lineEditOxTank")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditOxTank)
        self.lineEditOxFuel = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOxFuel.sizePolicy().hasHeightForWidth())
        self.lineEditOxFuel.setSizePolicy(sizePolicy)
        self.lineEditOxFuel.setObjectName("lineEditOxFuel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditOxFuel)
        self.lineEditRampUp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRampUp.setObjectName("lineEditRampUp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditRampUp)
        self.lineEditRampDown = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRampDown.sizePolicy().hasHeightForWidth())
        self.lineEditRampDown.setSizePolicy(sizePolicy)
        self.lineEditRampDown.setObjectName("lineEditRampDown")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditRampDown)
        self.spinBoxFlowModel = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFlowModel.sizePolicy().hasHeightForWidth())
        self.spinBoxFlowModel.setSizePolicy(sizePolicy)
        self.spinBoxFlowModel.setObjectName("spinBoxFlowModel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBoxFlowModel)
        self.labelThroatA = QtWidgets.QLabel(self.centralwidget)
        self.labelThroatA.setObjectName("labelThroatA")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelThroatA)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.lineEditThroatA = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditThroatA.sizePolicy().hasHeightForWidth())
        self.lineEditThroatA.setSizePolicy(sizePolicy)
        self.lineEditThroatA.setObjectName("lineEditThroatA")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditThroatA)
        self.labelOxfuel = QtWidgets.QLabel(self.centralwidget)
        self.labelOxfuel.setObjectName("labelOxfuel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelOxfuel)
        self.labelExitA = QtWidgets.QLabel(self.centralwidget)
        self.labelExitA.setObjectName("labelExitA")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelExitA)
        self.labelRampUp = QtWidgets.QLabel(self.centralwidget)
        self.labelRampUp.setObjectName("labelRampUp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelRampUp)
        self.labelRampDown = QtWidgets.QLabel(self.centralwidget)
        self.labelRampDown.setObjectName("labelRampDown")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelRampDown)
        self.labelTimeStep = QtWidgets.QLabel(self.centralwidget)
        self.labelTimeStep.setObjectName("labelTimeStep")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelTimeStep)
        self.labelConvWeight = QtWidgets.QLabel(self.centralwidget)
        self.labelConvWeight.setObjectName("labelConvWeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelConvWeight)
        self.labelFlowModel = QtWidgets.QLabel(self.centralwidget)
        self.labelFlowModel.setObjectName("labelFlowModel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelFlowModel)
        self.labelIntType = QtWidgets.QLabel(self.centralwidget)
        self.labelIntType.setObjectName("labelIntType")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelIntType)
        self.checkBoxCalcCf = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCalcCf.setText("")
        self.checkBoxCalcCf.setObjectName("checkBoxCalcCf")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBoxCalcCf)
        self.labelCalcCf = QtWidgets.QLabel(self.centralwidget)
        self.labelCalcCf.setObjectName("labelCalcCf")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelCalcCf)
        self.labelC12 = QtWidgets.QLabel(self.centralwidget)
        self.labelC12.setObjectName("labelC12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelC12)
        self.lineEditC12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditC12.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditC12.sizePolicy().hasHeightForWidth())
        self.lineEditC12.setSizePolicy(sizePolicy)
        self.lineEditC12.setObjectName("lineEditC12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEditC12)
        self.spinBoxIntType = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxIntType.sizePolicy().hasHeightForWidth())
        self.spinBoxIntType.setSizePolicy(sizePolicy)
        self.spinBoxIntType.setObjectName("spinBoxIntType")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinBoxIntType)
        self.lineEditTimeStep = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTimeStep.sizePolicy().hasHeightForWidth())
        self.lineEditTimeStep.setSizePolicy(sizePolicy)
        self.lineEditTimeStep.setObjectName("lineEditTimeStep")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditTimeStep)
        self.lineEditConvWeight = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConvWeight.sizePolicy().hasHeightForWidth())
        self.lineEditConvWeight.setSizePolicy(sizePolicy)
        self.lineEditConvWeight.setObjectName("lineEditConvWeight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditConvWeight)
        self.lineEditExitA = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditExitA.sizePolicy().hasHeightForWidth())
        self.lineEditExitA.setSizePolicy(sizePolicy)
        self.lineEditExitA.setObjectName("lineEditExitA")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditExitA)
        VariablesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VariablesWindow)
        self.statusbar.setObjectName("statusbar")
        VariablesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VariablesWindow)
        self.checkBoxCalcCf.toggled['bool'].connect(self.lineEditC12.setEnabled)
        self.buttonBox.clicked['QAbstractButton*'].connect(VariablesWindow.close)
        QtCore.QMetaObject.connectSlotsByName(VariablesWindow)
        VariablesWindow.setTabOrder(self.lineEditOxTank, self.lineEditThroatA)
        VariablesWindow.setTabOrder(self.lineEditThroatA, self.lineEditExitA)
        VariablesWindow.setTabOrder(self.lineEditExitA, self.lineEditOxFuel)
        VariablesWindow.setTabOrder(self.lineEditOxFuel, self.lineEditRampUp)
        VariablesWindow.setTabOrder(self.lineEditRampUp, self.lineEditRampDown)
        VariablesWindow.setTabOrder(self.lineEditRampDown, self.lineEditTimeStep)
        VariablesWindow.setTabOrder(self.lineEditTimeStep, self.lineEditConvWeight)
        VariablesWindow.setTabOrder(self.lineEditConvWeight, self.spinBoxFlowModel)
        VariablesWindow.setTabOrder(self.spinBoxFlowModel, self.spinBoxIntType)
        VariablesWindow.setTabOrder(self.spinBoxIntType, self.checkBoxCalcCf)
        VariablesWindow.setTabOrder(self.checkBoxCalcCf, self.lineEditC12)

    def retranslateUi(self, VariablesWindow):
        _translate = QtCore.QCoreApplication.translate
        VariablesWindow.setWindowTitle(_translate("VariablesWindow", "Variables"))
        self.labelOxTank.setText(_translate("VariablesWindow", "Oxidizer Tank Volume (L)"))
        self.labelThroatA.setText(_translate("VariablesWindow", "Nozzle Throat Area (cm²)"))
        self.labelOxfuel.setText(_translate("VariablesWindow", "Average O/F Ratio"))
        self.labelExitA.setText(_translate("VariablesWindow", "Nozzle Exit Area (cm²)"))
        self.labelRampUp.setText(_translate("VariablesWindow", "Ramp Up Time (s)"))
        self.labelRampDown.setText(_translate("VariablesWindow", "Ramp Down Time (s)"))
        self.labelTimeStep.setText(_translate("VariablesWindow", "Time Step (s)"))
        self.labelConvWeight.setText(_translate("VariablesWindow", "Convergence Weighting"))
        self.labelFlowModel.setText(_translate("VariablesWindow", "Flow Model"))
        self.labelIntType.setText(_translate("VariablesWindow", "Integration Type"))
        self.labelCalcCf.setText(_translate("VariablesWindow", "Calculate Cf"))
        self.labelC12.setText(_translate("VariablesWindow", "C12"))

